### ISSUE TITLE
Unclear which extra settings and functions can be removed if not OpenSesame

### ISSUE THREAD

**Issue by Pizzanomicon** [dschreij/anaconda-env-to-osx-app#2]
Is everything after line 109 removable?
Recommend a clear #============= End OpenSesame-unique =========== flag

**Comment by dschreij** [comment]
Yes, that's the case. The main script checks if there is an extra() function defined in the settings file, and if there is, calls it at the end of the main build process. As you can see, below line 109 you only see functions that are used in the extra() function and these are all opensesame specific
